/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as DiscographySlugImport } from "./routes/discography.$slug";
import { Route as DiscographyIndexImport } from "./routes/discography.index";
import { Route as GalleryImport } from "./routes/gallery";
import { Route as IndexImport } from "./routes/index";
import { Route as ProfileImport } from "./routes/profile";
import { Route as VideoImport } from "./routes/video";

// Create/Update Routes

const VideoRoute = VideoImport.update({
  id: "/video",
  path: "/video",
  getParentRoute: () => rootRoute,
} as any);

const ProfileRoute = ProfileImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRoute,
} as any);

const GalleryRoute = GalleryImport.update({
  id: "/gallery",
  path: "/gallery",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const DiscographyIndexRoute = DiscographyIndexImport.update({
  id: "/discography/",
  path: "/discography/",
  getParentRoute: () => rootRoute,
} as any);

const DiscographySlugRoute = DiscographySlugImport.update({
  id: "/discography/$slug",
  path: "/discography/$slug",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/gallery": {
      id: "/gallery";
      path: "/gallery";
      fullPath: "/gallery";
      preLoaderRoute: typeof GalleryImport;
      parentRoute: typeof rootRoute;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileImport;
      parentRoute: typeof rootRoute;
    };
    "/video": {
      id: "/video";
      path: "/video";
      fullPath: "/video";
      preLoaderRoute: typeof VideoImport;
      parentRoute: typeof rootRoute;
    };
    "/discography/$slug": {
      id: "/discography/$slug";
      path: "/discography/$slug";
      fullPath: "/discography/$slug";
      preLoaderRoute: typeof DiscographySlugImport;
      parentRoute: typeof rootRoute;
    };
    "/discography/": {
      id: "/discography/";
      path: "/discography";
      fullPath: "/discography";
      preLoaderRoute: typeof DiscographyIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/gallery": typeof GalleryRoute;
  "/profile": typeof ProfileRoute;
  "/video": typeof VideoRoute;
  "/discography/$slug": typeof DiscographySlugRoute;
  "/discography": typeof DiscographyIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/gallery": typeof GalleryRoute;
  "/profile": typeof ProfileRoute;
  "/video": typeof VideoRoute;
  "/discography/$slug": typeof DiscographySlugRoute;
  "/discography": typeof DiscographyIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/gallery": typeof GalleryRoute;
  "/profile": typeof ProfileRoute;
  "/video": typeof VideoRoute;
  "/discography/$slug": typeof DiscographySlugRoute;
  "/discography/": typeof DiscographyIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/gallery"
    | "/profile"
    | "/video"
    | "/discography/$slug"
    | "/discography";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/gallery"
    | "/profile"
    | "/video"
    | "/discography/$slug"
    | "/discography";
  id:
    | "__root__"
    | "/"
    | "/gallery"
    | "/profile"
    | "/video"
    | "/discography/$slug"
    | "/discography/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  GalleryRoute: typeof GalleryRoute;
  ProfileRoute: typeof ProfileRoute;
  VideoRoute: typeof VideoRoute;
  DiscographySlugRoute: typeof DiscographySlugRoute;
  DiscographyIndexRoute: typeof DiscographyIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  ProfileRoute: ProfileRoute,
  VideoRoute: VideoRoute,
  DiscographySlugRoute: DiscographySlugRoute,
  DiscographyIndexRoute: DiscographyIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/gallery",
        "/profile",
        "/video",
        "/discography/$slug",
        "/discography/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/gallery": {
      "filePath": "gallery.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/video": {
      "filePath": "video.tsx"
    },
    "/discography/$slug": {
      "filePath": "discography.$slug.tsx"
    },
    "/discography/": {
      "filePath": "discography.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
